export const toolbarTips = {
  'ql-bold': '加粗',
  'ql-italic': '倾斜',
  'ql-underline': '下划线',
  'ql-header': '段落格式',
  'ql-strike': '删除线',
  'ql-blockquote': '块引用',
  'ql-code': '插入代码',
  'ql-code-block': '插入代码段',
  'ql-size': '字体大小',
  'ql-list[value="ordered"]': '编号列表',
  'ql-list[value="bullet"]': '项目列表',
  'ql-header[value="1"]': 'h1',
  'ql-header[value="2"]': 'h2',
  'ql-align': '对齐方式',
  'ql-color': '字体颜色',
  'ql-background': '背景颜色',
  'ql-image': '图像',
  'ql-video': '视频',
  'ql-link': '添加链接',
  'ql-formula': '插入公式',
  'ql-clean': '清除格式',
  'ql-direction': '文字方向',
  'ql-indent[value="-1"]': '向左缩进',
  'ql-indent[value="+1"]': '向右缩进',
  'ql-header ql-picker-label': '标题大小',
  'ql-script[value="sub"]': '下标',
  'ql-script[value="super': '上标',
  'ql-redo': '前进',
  'ql-undo': '撤销',
}
